name: Test

on:
#   push:
#     branches: [ master ]
  pull_request:
    branches: [ master ]
  # allow running manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Nothing to test!"
